language: ruby
cache: bundler
bundler_args: --without yard guard benchmarks
notifications:
  email: false
addons:
  code_climate:
    repo_token: 251b82d126332fb2f97482d061d2a35b3fa5acf793eb85b223d7bac04786f61b

after_success:
  - bundle exec codeclimate-test-reporter

before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb
  - sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
  - sudo service rethinkdb restart
  - gem install bundler -v '~> 1.10'

matrix:
  allow_failures:
    - rvm: ruby-head
  include:
  - rvm: 2.2.6
  - rvm: 2.3.3
  - rvm: ruby-head
